//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Services_Id { get; set; }
        public string p2p_title { get; set; }
        public string p2p_description { get; set; }
        public string air_title { get; set; }
        public string air_description { get; set; }
        public string corporate_title { get; set; }
        public string corporate_description { get; set; }
    }
}
